version: '3.8'
services:
  mysql:
    build: ./APDATABASE
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=APDATA
      - MYSQL_USER=apdata
      - MYSQL_PASSWORD=apdata
    ports:
      - "3006:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p", "root"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build: ./APFRONT

    container_name: frontend-container
    ports:
      - "4173:4173"
    networks:
      - app-network

  python-api:
    build: ./APYTHON
    container_name: python-api-container
    depends_on:
      - frontend
      - mysql
    ports:
      - "8000:8000"
    networks:
      - app-network

  backend: 
    build: ./APBACK
    container_name: backend-container
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/APDATA
      - SPRING_DATASOURCE_USERNAME=apdata
      - SPRING_DATASOURCE_PASSWORD=apdata
    ports:
      - "8095:8095"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge