apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: pestana273/backend:1
        ports:
        - containerPort: 8095
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/APDATA
        - name: SPRING_DATASOURCE_USERNAME
          value: apdata
        - name: SPRING_DATASOURCE_PASSWORD
          value: apdata
